# Generated by Django 3.2 on 2022-06-27 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_type', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=250)),
                ('civil_Id', models.CharField(max_length=200, unique=True)),
                ('Date_Of_Birth', models.DateField()),
                ('email', models.CharField(max_length=200)),
                ('adress', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('ID_photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('uplode', models.ImageField(blank=True, null=True, upload_to='images')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('nationality', models.CharField(max_length=200)),
                ('parents_contact', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PatientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_service', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
    ]
