# Generated by Django 3.2 on 2022-06-04 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_type', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PatientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_service', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
                ('main_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kshapp.section')),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapist_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.section')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('civil_Id', models.CharField(max_length=200, unique=True)),
                ('Date_Of_Birth', models.DateField()),
                ('email', models.CharField(max_length=200)),
                ('date_join', models.DateField()),
                ('adress', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('ID_photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('uplode', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Gender', models.CharField(blank=True, choices=[('Mail', 'Mail'), ('Femel', 'Femel')], max_length=200, null=True)),
                ('Nationality', models.CharField(max_length=200)),
                ('Parents_contact', models.CharField(max_length=200)),
                ('patient_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.patienttype')),
                ('type_disability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.disability')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, choices=[('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('1', '1'), ('2', '2')], max_length=200, null=True, unique=True)),
                ('note', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('Attend', 'Attend'), ('Absent', 'Absent'), ('Excuse of Child', 'Excuse of Child'), ('Excuse of therapist', 'Excuse of therapist')], max_length=200, null=True)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.patient')),
                ('therapist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.therapist')),
            ],
        ),
    ]
