# Generated by Django 3.2 on 2022-06-30 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, choices=[('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('1', '1'), ('2', '2')], max_length=200, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('Attend', 'Attend'), ('Absent', 'Absent'), ('Excuse of Child', 'Excuse of Child'), ('Excuse of therapist', 'Excuse of therapist')], max_length=200, null=True)),
                ('action', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_type', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=250)),
                ('civil_Id', models.CharField(max_length=200, unique=True)),
                ('Date_Of_Birth', models.DateField()),
                ('email', models.CharField(max_length=200)),
                ('adress', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('ID_photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('uplode', models.ImageField(blank=True, null=True, upload_to='images')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('nationality', models.CharField(max_length=200)),
                ('parents_contact', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PatientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_service', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
    ]
