# Generated by Django 3.2 on 2022-06-27 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('kshapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('phone', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.section')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
        migrations.AddField(
            model_name='section',
            name='main_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kshapp.section'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.patienttype'),
        ),
        migrations.AddField(
            model_name='patient',
            name='type_disability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.disability'),
        ),
    ]
