# Generated by Django 3.2 on 2022-06-25 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kshapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='main_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kshapp.section'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.patienttype'),
        ),
        migrations.AddField(
            model_name='patient',
            name='type_disability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.disability'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kshapp.section'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='therapist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.therapist'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time', 'therapist_name', 'patient_name')},
        ),
    ]
