# Generated by Django 3.2 on 2022-06-30 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('kshapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('phone', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('avtar', models.ImageField(blank=True, upload_to='images/therapist')),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.section')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
        migrations.AddField(
            model_name='section',
            name='main_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kshapp.section'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.patienttype'),
        ),
        migrations.AddField(
            model_name='patient',
            name='type_disability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.disability'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kshapp.section'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='kshapp.therapist'),
        ),
        migrations.CreateModel(
            name='TherapistAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.appointment')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kshapp.therapist')),
            ],
            options={
                'unique_together': {('therapist', 'appointment')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time', 'patient', 'therapist')},
        ),
    ]
