# Generated by Django 3.2 on 2022-07-03 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kshapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ID_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/patients'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/patients'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='uplode',
            field=models.ImageField(blank=True, null=True, upload_to='images/patients'),
        ),
        migrations.DeleteModel(
            name='TherapistAppointment',
        ),
    ]
