# Generated by Django 3.2 on 2022-06-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kshapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='avtar',
            field=models.ImageField(blank=True, upload_to='images/therapist'),
        ),
    ]
