# Generated by Django 3.2 on 2022-07-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kshapp', '0003_auto_20220703_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='therapist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='kshapp.therapist'),
            preserve_default=False,
        ),
    ]
