# Generated by Django 3.2 on 2022-06-09 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kshapp', '0003_appointment_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kshapp.section'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='action',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=200, null=True),
        ),
    ]
