# Generated by Django 3.2 on 2022-07-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kshapp', '0004_alter_appointment_therapist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('Attend', 'Attend'), ('Absent', 'Absent'), ('Compensate', 'Compensate')], max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time', 'therapist')},
        ),
    ]
