# Generated by Django 3.2 on 2022-07-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kshapp', '0005_auto_20220716_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='uplode',
            field=models.FileField(blank=True, null=True, upload_to='images/patients'),
        ),
    ]
