# Generated by Django 3.2 on 2022-07-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kshapp', '0006_alter_patient_uplode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(blank=True, choices=[('8:00', '8:00'), ('8:45', '8:45'), ('9:30', '9:30'), ('10:15', '10:15'), ('11:00', '11:00'), ('11:45', '11:45'), ('12:30', '12:30'), ('01:15', '01:15')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='parents_contact',
            field=models.CharField(choices=[('Kuwaiti', 'Kuwaiti'), ('Egyption', 'Egyption'), ('Iraqi', 'Iraqi'), ('Jordanian', 'Jordanian'), ('Non-Kuwaiti', 'Non-Kuwaiti'), ('Saudi', 'Saudi'), ('Syrian', 'Syrian'), ('Yemeni', 'Yemeni'), ('Indian', 'Indian')], max_length=200),
        ),
    ]
