# Generated by Django 3.2 on 2022-07-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kshapp', '0009_alter_patient_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_type',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.ManyToManyField(to='kshapp.PatientType'),
        ),
    ]
