# Generated by Django 3.2 on 2022-07-25 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kshapp', '0011_auto_20220725_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='type_disability',
        ),
        migrations.AddField(
            model_name='patient',
            name='type_disability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kshapp.disability'),
            preserve_default=False,
        ),
    ]
