# Generated by Django 3.2 on 2022-10-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kshapp', '0007_alter_appointment_unique_together'),
        ('kshapp', '0012_auto_20220725_2139'),
    ]

    operations = [
    ]
