# Generated by Django 3.2 on 2022-10-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kshapp', '0013_merge_20221006_1257'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time', 'therapist')},
        ),
    ]
